<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Dynamic\Aneiang.Pa.Dynamic\Aneiang.Pa.Dynamic.csproj" />
    <ProjectReference Include="..\Modules\Lottery\Aneiang.Pa.Lottery\Aneiang.Pa.Lottery.csproj" />
    <ProjectReference Include="..\Modules\News\Aneiang.Pa.News\Aneiang.Pa.News.csproj" />
  </ItemGroup>

</Project>
