<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageId>Aneiang.Pa.Abstractions</PackageId>
    <Description>Aneiang.Pa 4.0 核心抽象（接口/模型）</Description>
    <PackageTags>scraper;abstractions;interfaces;models</PackageTags>
  </PropertyGroup>

</Project>
