<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageId>Aneiang.Pa.Client</PackageId>
    <Description>Aneiang.Pa 4.0 — HTTP 强类型客户端</Description>
    <PackageTags>scraper;http-client;sdk</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aneiang.Pa.Abstractions\Aneiang.Pa.Abstractions.csproj" />
  </ItemGroup>
</Project>
